In [1]:
import numpy as np

In [2]:
import grpc

import evocraft_ga.external.minecraft_pb2_grpc as minecraft_pb2_grpc
from evocraft_ga.external.minecraft_pb2 import *  # noqa

channel = grpc.insecure_channel("localhost:5001")
client = minecraft_pb2_grpc.MinecraftServiceStub(channel)
x = 20
y = 10
z = 20
client.fillCube(
    FillCubeRequest(  # Clear a 20x10x20 working area
        cube=Cube(
            min=Point(x=x - 10, y=y, z=z - 10), max=Point(x=x + 10, y=y + 10, z=z + 10)
        ),
        type=AIR,
    )
)
client.spawnBlocks(
    Blocks(
        blocks=[  # Spawn a flying machine
            # Lower layer
            Block(
                position=Point(x=1 + x, y=5 + y, z=1 + z),
                type=REDSTONE_BLOCK,
                orientation=NORTH,
            ),
            Block(
                position=Point(x=1 + x, y=5 + y, z=2 + z), type=REDSTONE_BLOCK, orientation=NORTH
            ),
            Block(
                position=Point(x=1 + x, y=5 + y, z=3 + z),
                type=REDSTONE_BLOCK,
                orientation=SOUTH,
            ),
            Block(
                position=Point(x=1 + x, y=5 + y, z=4 + z),
                type=REDSTONE_BLOCK,
                orientation=NORTH,
            ),
            Block(
                position=Point(x=1 + x, y=5 + y, z=5 + z),
                type=REDSTONE_BLOCK,
                orientation=NORTH,
            ),
            # Upper layer
            Block(
                position=Point(x=1 + x, y=5 + y, z=6 + z),
                type=REDSTONE_BLOCK,
                orientation=NORTH,
            ),
            Block(
                position=Point(x=1 + x, y=5 + y, z=7 + z),
                type=REDSTONE_BLOCK,
                orientation=NORTH,
            ),
            # Activate
            Block(
                position=Point(x=1 + x, y=5 + y, z=8 + z),
                type=REDSTONE_BLOCK,
                orientation=NORTH,
            ),
        ]
    )
)


blocks = client.readCube(
    Cube(min=Point(x=x - 10, y=y, z=z - 10), max=Point(x=x + 10, y=y + 10, z=z + 10))
)

for b in blocks.blocks:
    if b.type != 5:
        print(b)

position {
  x: 21
  y: 15
  z: 21
}
type: REDSTONE_BLOCK

position {
  x: 21
  y: 15
  z: 22
}
type: REDSTONE_BLOCK

position {
  x: 21
  y: 15
  z: 23
}
type: REDSTONE_BLOCK

position {
  x: 21
  y: 15
  z: 24
}
type: REDSTONE_BLOCK

position {
  x: 21
  y: 15
  z: 25
}
type: REDSTONE_BLOCK

position {
  x: 21
  y: 15
  z: 26
}
type: REDSTONE_BLOCK

position {
  x: 21
  y: 15
  z: 27
}
type: REDSTONE_BLOCK

position {
  x: 21
  y: 15
  z: 28
}
type: REDSTONE_BLOCK



In [5]:
a = np.zeros(shape=(10,10,10))

In [8]:
a[0][0][0] = 1

In [9]:
a

array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [12]:
a = np.random.randint(900,size=(5,5,5))

In [13]:
a

array([[[491, 804, 117, 679, 199],
        [207, 475,  66, 108, 760],
        [  8, 241, 343, 606, 505],
        [630, 185, 523, 400,  22],
        [590, 387, 506,  76, 462]],

       [[525, 649, 512, 794, 576],
        [814, 234, 538, 485, 838],
        [876, 250, 424, 757, 550],
        [ 68, 568, 602, 541,  96],
        [868, 259,  34,  24, 832]],

       [[362, 210, 477, 129, 113],
        [746, 878, 811, 598, 119],
        [385,  72,  63, 586, 834],
        [341, 173, 427, 170, 555],
        [285, 395, 167, 831,  21]],

       [[ 93, 148,  49, 837,  56],
        [ 53, 854, 209, 322, 741],
        [627, 699, 350, 368, 270],
        [360, 754, 669,  30, 860],
        [839, 658, 516, 279, 713]],

       [[162, 338, 823, 599,  94],
        [282, 240, 685,  77, 858],
        [837, 579, 822,  98, 309],
        [623, 344, 653,  22, 270],
        [519, 389, 176, 629, 400]]])

In [28]:
test = np.ones(27).reshape(3,3,3)

In [29]:
test

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [30]:
for x in np.ndindex(test.shape):
    print(test[x])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [20]:
n = np.random.uniform(0,1, size=(2,3))

In [40]:
np.zeros(shape=(3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
np.round(n)

array([[1., 1., 0.],
       [1., 0., 1.]])

In [402]:
class Spawner:
    def __init__(self, start_x=20, start_y=10, start_z=20, cube_len=10, block_type=REDSTONE_BLOCK, orientation=SOUTH, criteria=.8):
        self.start_x = start_x
        self.start_y = start_y
        self.start_z = start_z
        self.cube_len = cube_len
        self.block_type = block_type
        self.criteria = criteria
        self.orientation = orientation
        self.channel = grpc.insecure_channel("localhost:5001")
        self.client = minecraft_pb2_grpc.MinecraftServiceStub(channel)

    def create_block(self, x, y, z):
        return Block(
                position=Point(x=x, y=y, z=z),
                type=self.block_type,
                orientation=self.orientation,
            )  
    
    def clear_blocks(self, x_min, y_min, z_min):
        
        self.client.fillCube(
            FillCubeRequest(  # Clear a 20x10x20 working area
                cube=Cube(
                    min=Point(x=x_min, y=y_min, z=z_min), max=Point(x=x_min + self.cube_len, y=y_min + self.cube_len, z=z_min + self.cube_len)
                ),
                type=AIR,
            )
        )

    def _populate_arr(self, arr, x_min, y_min, z_min):
        blocks = []
        self.clear_blocks(x_min,y_min,z_min)
        for coord in np.ndindex(arr.shape):
            if arr[coord] >= self.criteria:
                block = self.create_block(x=x_min+coord[0], y=y_min+coord[1], z=z_min+coord[2])
                blocks.append(block)
        blocks = Blocks(blocks=blocks)
        client.spawnBlocks(blocks)
    
    def populate(self, cube_probs):
        for i in range(len(cube_probs)):
            dist = i*5 + i*self.cube_len
            self._populate_arr(cube_probs[i], self.start_x+dist,self.start_y, self.start_z)

    def clear_population(self, population_size):
        for i in range(population_size):
            dist = i*5 + i*self.cube_len
            self.clear_blocks(self.start_x+dist,self.start_y, self.start_z)
    

In [384]:
l = [np.ones((10,10,10)) for i in range(10)]

In [385]:
s = Spawner()

In [388]:
s.populate(l)

In [66]:
def multi_populate(population_len, border_len=5, x_min=20, y_min=10, z_min=20, cube_len=20):
    x = x_min
    y = y_min
    z = z_min
    for i in range(population_len):
        dist = i*border_len + i*cube_len
        populate_arr(np.random.uniform(0,1, size=(cube_len,cube_len,cube_len)), x+dist,y, z, cube_len)

In [67]:
def multi_clear(population_len, border_len=5, x_min=20, y_min=10, z_min=20, cube_len=20):
    x = x_min
    y = y_min
    z = z_min
    for i in range(population_len):
        dist = i*border_len + i*cube_len
        clear_blocks(x+dist,y, z, cube_len)

In [84]:
multi_clear(10, cube_len=10)

In [80]:
multi_populate(10, cube_len=10)

In [268]:
torch.squeeze(torch.from_numpy(n))

tensor([0.4966, 0.4996, 0.5044, 0.5001, 0.4977, 0.5002, 0.5086, 0.4904, 0.5096,
        0.4958, 0.5045, 0.5096, 0.4921, 0.4991, 0.5035, 0.4970, 0.4953, 0.5022,
        0.5035, 0.5021, 0.5136, 0.5011, 0.4981, 0.4886, 0.4965, 0.4977, 0.4935,
        0.5031, 0.4920, 0.4927, 0.5028, 0.5085, 0.4997, 0.4912, 0.4909, 0.5008,
        0.5075, 0.4986, 0.5040, 0.4916, 0.4920, 0.4946, 0.5024, 0.5076, 0.5006,
        0.5003, 0.5080, 0.5012, 0.4972, 0.4879, 0.4980, 0.5045, 0.5004, 0.4995,
        0.4970, 0.4990, 0.5037, 0.5069, 0.5068, 0.4873, 0.5097, 0.4981, 0.5007,
        0.4939, 0.5029, 0.5030, 0.4917, 0.5041, 0.5007, 0.4890, 0.5066, 0.4922,
        0.4868, 0.5017, 0.5021, 0.4977, 0.4980, 0.4946, 0.4970, 0.5006, 0.5083,
        0.4896, 0.4929, 0.4909, 0.4965, 0.4974, 0.4930, 0.5008, 0.5024, 0.5002,
        0.5079, 0.5048, 0.4984, 0.5117, 0.5018, 0.4942, 0.4986, 0.5052, 0.4916,
        0.5017, 0.4926, 0.4988, 0.5056, 0.5024, 0.5014, 0.4920, 0.4903, 0.5060,
        0.5110, 0.5020, 0.5044, 0.5014, 

In [364]:
import torch
from torch import nn
import typing
import numpy as np
import sys

def create_linear_torch(
    input_dims, output_dims, bias=False, relu=False, batch_norm=False
):
    layers = []
    lin = torch.nn.Linear(input_dims, output_dims, bias=bias)
    layers.append(lin)
    if batch_norm:
        layers.append(torch.nn.BatchNorm1d(output_dims))
    if relu:
        layers.append(torch.nn.ReLU())
    return torch.nn.Sequential(*layers)

class Linear(nn.Module):
    def __init__(self, noise_dims, x_dims, y_dims, z_dims):
        super(Linear, self).__init__()
        self.noise_dims = noise_dims
        self.x_dims = x_dims
        self.y_dims = y_dims
        self.z_dims = z_dims

        self.linear1 = create_linear_torch(noise_dims, 64, relu=True)
        self.linear2 = create_linear_torch(64, 256, relu=True)
        self.linear3 = create_linear_torch(256, 512, relu=True)
        self.output_linear = create_linear_torch(256, x_dims*y_dims*z_dims)
        self.sigmoid = nn.Sigmoid()
        self.layers = [
            self.linear1,
            self.linear2,
#             self.linear3,
            self.output_linear,
            self.sigmoid
        ]
        self._net = nn.Sequential(*self.layers)

    def forward(self, x):
        x = self._net(x)
        return x

    def generate(self, mean=0.0, std=1.0, to_numpy=False, squeeze=False):
#         if seed is None:
#             seed = np.random.randint(2**31 - 1)
#         rs = np.random.RandomState(seed)
        noise = torch.from_numpy(np.random.normal(loc=mean, scale=std, size=(1, self.noise_dims))).float()
        out = self.forward(noise)
        if squeeze:
            out = torch.squeeze(out)
        if to_numpy:
            out = out.detach().numpy()
        return out

In [365]:
import attr

In [366]:
from __future__ import annotations
import copy

@attr.s
class Genome:
    noise_dims: int = attr.ib()
    cube_dims : int = attr.ib()
    seeds : typing.List[int] = attr.ib(default=[])
    noise_stdev : float = attr.ib(default=1.0)
    # set later
    model = attr.ib(init=False)

    def __attrs_post_init__(self):
        self._verify_seeds(self.seeds)
        self.model = Linear(self.noise_dims, self.cube_dims, self.cube_dims, self.cube_dims)
        self.initialize_weights()
        
    def _verify_seeds(self, seeds):
        if len(seeds) == 0:
            seeds = [np.random.randint(1, high=2 ** 31 - 1)]
        self.seeds = seeds.copy()

    def initialize_weights(self) -> None:
        num_seeds = len(self.seeds)

        rs = np.random.RandomState(self.seeds[0])
        for n, W in self.model.named_parameters():
            if any(x in n for x in ["weight", "bias"]):
                weights = rs.normal(loc=0.0, scale=self.noise_stdev, size=W.size())
                W.data = torch.from_numpy(weights).float()

        for seed_num in range(1, num_seeds):
            rs = np.random.RandomState(self.seeds[seed_num])
            for name, W in self.model.named_parameters():
                if any(x in name for x in ["weight", "bias"]):
                    weights = (
                        rs.normal(loc=0.0, scale=1.0, size=W.size()) * self.noise_stdev
                    )
                    W.data = W.data + torch.from_numpy(weights).float()

    def mutate(self):
        new_seed = np.random.randint(1, high=2 ** 31 - 1)
        self.seeds.append(new_seed)
        self.initialize_weights()

    def generate(self, to_numpy=False, squeeze=False):
        return self.model.generate(to_numpy=to_numpy, squeeze=squeeze)
    
    def copy_parameters(self, genome: Genome):
        self.seeds = copy.deepcopy(genome.seeds)
    

In [367]:
from tqdm import tqdm

In [368]:
from collections import deque

In [369]:
import sklearn
from sklearn.neighbors import NearestNeighbors
import numpy as np

def cross_entropy(x, y):
    N = x.shape[0]
    ce = -np.sum(y * np.log(x)) / N
    return ce

class NoveltySearch:
    def __init__(self, num_neighbors, maxlen=200):
        self.num_neighbors = num_neighbors
        self._bcs = deque([], maxlen=maxlen)
        self._knn = NearestNeighbors(n_neighbors=num_neighbors,
                 algorithm='auto',
                 metric=lambda a,b: cross_entropy(a,b)
                 )
    
    def apply(self, bcs):
        for bc in bcs:
            self._bcs.append(bc)
        neighbors = self._knn.fit(np.array(self._bcs))
        distances, indices = self._knn.kneighbors(np.array(bcs))
        return np.mean(distances, axis=1)



In [403]:
import random

@attr.s
class GeneticAlgorithm:
    population_size : int = attr.ib(default=50)
    num_elites : int = attr.ib(default=5)
    noise_dims: int = attr.ib(default=100)
    cube_dims : int = attr.ib(default=10)
    noise_stdev: float = attr.ib(default=0.02)
    num_neighbors : int = attr.ib(default=5)
    num_bcs : int = attr.ib(default=200)
        
    spawner: Spawner = attr.ib(default=None)
    genomes : typing.List[Genome] = attr.ib(init=False)
    
    def __attrs_post_init__(self):
        self.populate()
        self.novelty_search = NoveltySearch(num_neighbors=self.num_neighbors, maxlen=self.num_bcs)
        if self.spawner is None:
            self.spawner = Spawner(cube_len=self.cube_dims)

    def populate(self):
        self.genomes = []
        for i in range(self.population_size):
            genome = Genome(noise_dims=self.noise_dims,
                            cube_dims=self.cube_dims,
                            noise_stdev=self.noise_stdev)
            self.genomes.append(genome)
    
    def evolve(self, num_generations=100):
        try:
            bar = tqdm(np.arange(num_generations))
            for i in bar:
                outputs = [genome.generate(to_numpy=True, squeeze=True) for genome in self.genomes]
                self.spawn(outputs)
                fitnesses = self.novelty_search.apply(outputs)
                max_fitness = np.max(fitnesses)
                bar.set_description("Generation: {} with max fitness: {}".format(i, max_fitness))
                self.reproduce(fitnesses)
        except:
            self.spawner.clear_population(self.population_size)
    
    def spawn(self, outputs):
        reshaped_outputs = [output.reshape(self.cube_dims, self.cube_dims, self.cube_dims) for output in outputs]
        self.spawner.populate(reshaped_outputs)
        
    def reproduce(self, fitnesses) -> None:
        """
            reproduces by taking the top N elites and copying + mutating their seeds
        """
        ranking = np.argsort(fitnesses)[::-1]
        elite_ranking = ranking[: self.num_elites]
        elite_ranking_set = set(elite_ranking)
        best_genome_index = elite_ranking[0]

        for genome_index in range(len(self.genomes)):
            # first mutate non elite agents
            if genome_index not in elite_ranking_set:
                random_elite_index = random.choice(elite_ranking)
                random_elite = self.genomes[random_elite_index]
                self.genomes[genome_index].copy_parameters(
                    random_elite
                )  # copy seeds
                self.genomes[genome_index].mutate()

        for genome_index in elite_ranking_set:
            # mutate elites except the best one
            if genome_index != best_genome_index:
                self.genomes[genome_index].mutate()
    
        

In [406]:
g = GeneticAlgorithm(noise_stdev=0.05)

In [ ]:
g.evolve()

Generation: 0 with max fitness: 0.34761316487803867:   1%|          | 1/100 [00:05<09:53,  6.00s/it]